// <auto-generated />
namespace Bede.Go.Contracts.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class AddLocations : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201712071211516_AddLocations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1Zy27jNhTdF+g/CFq1BcZygmKQCZwZZPJC0DgJonS2AS3RDlGKVEkqsL+ti35Sf6GXkkVRpGTLSVy0QDeGRPE+eXhf/uuPPydflhkNXrCQhLOT8GA0DgPMEp4StjgJCzX/cBR++fz9d5OLNFsG3+p9h3ofUDJ5Ej4rlR9HkUyecYbkKCOJ4JLP1SjhWYRSHh2Ox0fRwTjCwCIEXkEweSiYIhkuX+D1jLME56pAdMpTTOV6Hb7EJdfgFmVY5ijBJ+FXnOLRFR8BjRIoUTIMTilBoEiM6XxHrcaftFahkQcSL0AztXpc5biUehJewa+9A/b8gletBVi6FzzHQq0e8HxNd52GQdSmi1xCQ2bRaNHwxNTHn8PgtqAUzSgszBGVOAzyj8ex4gJfYYYFUji9R0phwTQtLlVfu+A4/zjMC5+i8aH2QoQY4wopOGBPcUdN/VsrGisBWAmDS7LE6Q1mC/VslJ2iZb0Cj2HwKyMALSBSosC2cdX7ZqHnRCoEOKkFn+OEZIiGwb2ApzV+j8IgTpBmedjhvM0CYoWEeiSNaefg3+p9G6db9EIWpescnjc8WXv0AdPyST6TvMLqSCPrqdlxKXj2wOkacubDU8wLUZrNu74+IrHAqq3RJGpQvBHbRvj/+G6fGlsQVaT7w9oN6LFXAadJUkB4XL2TgD5EnUrJE1I61QqXTz24umBpsBHhVUSp7wYEkIIqklOSgOiT8CfP6D6G9aWwGDb3rM10PBoduLZaVvnXRyceRACda4N1QrriU7IQJYH+jJfKs1yTxlhZXoLM1Ti1ZbZnZZu4NqWLQWOmw8Syqa2GFYGsPZ0hyg0K287TKG4MjoayqE/QYmGZ7cadtnEduDWH1pQWUVVb1DVI1FOETKYozyHDWUXJeiWIq4rk7EO8e9mRVTyiRHZUH0ZbIwlCIlpg5yuIBk0viZAKUhWaIX1rz9LM27YbRGuhNlL9Y6txV+/Wz82FaFVoI7+Esv14CaZlENtLK7GDGZ+srAoRRaIjt5xxWmSsLz9toq5KGpv+tuMqbuLQ1Cc2l2Z1OCerELFZWcs+r0nkeNM9scg7MucOuec/CB3NnXwbQvpCzACU9JPuBylWcWAzsZZ34GXKgBYrszqcU5PvbU7N6j+PmHZM9oOKlXe2xQ5r65AYoZOK457O5OK7ZBBcDJsu3GivGOG76rXOm6/Ua2d1wMkpKUu3a6mrP1P5DbTWzbs+DLz0624xIDRp2Em3k3Xq2z4Y8HJhtUVXvPyFpDoPxiupcDbSG0bx7/SMEoB9s2GKGJljqR75b1gPOSBVv364YNoOKVP6b5wwzMiCaOu3tls7dh72cIC9IJE8I/FDhpY/vrXhT/fe8KfgATWo4e9p8598926y+T/Qp+8LJV6L/e6n67bY7y7AbbHfKOC9W+x2et25C/Z6s1e05wBCLDRAEIUMICGjE7/MuBeEJSRH1NXbT4NDwK0daVi6X85xjpmGrG3XEDlbcr7h69yzbQ7YcdTgt3vbpwy9Q4YqPQJsZxyOtoJlZ5feO3/YOH7oYt/fwe93OuEq3O4btg0lvDnGfuYPfqED+LH+JwHwSrJoWOjyjeGkhRyz55rNeY1iR6N6ixPNplghyH/oVCgyh8obPidYynK2/w3RArZcZDOcXrO7QuWFApNxNqOt1kJfhE3yyyFLW+fJXV4i4j1MADWJTuF37GtBaGr0vuwItj0s9A1bZzl9lkpnu8XKcLrlbCCjtftMYHjEWU6BmbxjMXrB/bpt92HbY5NzghYCZbYHq5W6ykEg2RIBAmyKRh68AlzTbPn5b8qS+FAZHAAA"; }
        }
    }
}
