// <auto-generated />
namespace Bede.Go.Contracts.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class InitialSetup : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201712071201373_InitialSetup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAMVYzW7jNhC+F+g7CDq1hxW9QRFkA3kXWTsJgq6TYJXudUFLY4coRaokFdjP1kMfqa/QoX5pSZbjTYJeBJGcf858M9K/f/8Tftqk3HsCpZkUU/99MPE9ELFMmFhP/dys3p35nz7+/FN4maQb71tNd2LpkFPoqf9oTHZOiI4fIaU6SFmspJYrE8QyJTSR5GQyOSPvJwRQhI+yPC/8mgvDUigWuJxJEUNmcsoXMgGuq308iQqp3i1NQWc0hqn/GRIIrmWAPEbR2Gjfu+CMoiER8NWRVk0+WKv8Rl9hS5px2DxsMyjUTv0vMqYG3XbJkPBeyQyU2TZUYs1MnoDvWd6pP4eYpZT73r3Ctyq+Z74XxZTj8Ynv3eac06VdrCjXyEjGNaAVb6rgIo5zDOn2lRSExImlu3+Jl2+2ToSv8dmJ7u+w3dlwrP0Kq4rvJum5RLqMXSctT+nejTCnvw34kJ2eR0YquAYBihpI7qkxoITlhcL0KsvOs9PnJdoHMjmxiUaoENKUyXTgLuyzNjQyCsvR967YBpIvINbmsTF2QTf1Dr763h+CYfUik1E5uM6V63Glc6YNxVJ8swyLDFXmgbWuzTG+5frYYqiLso4RFn/Qbh5IzDYD+3lpgYUyvPpKkwWca9lJz5I0AuNkMCJRK7eyqMjsQeWNmhbsSIl2NSqSPbAYLmiWYUI4MFnteFGJkbN30fFAmJYySKz9kaA0mrBC6Bo6p6gaLb1iShu8WbqkNvSzJO2RjQe1VuLGtosGbahravveXtlOjwj6COPG7QpdSbG0C6+gMWMImCpGWwFUDUDLTPI8FfvgaYy7rHiX/7aXPOMS2vJ1pbS7z5fk1KkrytkelFXh/Wip7ruh4S47bqbTc10za1HfnfMhe/eKbRrtsNTm+BihbXMdFNoeD0aWdELbT2XSyeVuvZBewXQaZ7f6xjCrS9Job7Crg1FhhReH57segJQktgfJJ5ZY8Ii22kAaWIIg+ovPOEN/W4IFFWwF2jzIP8HOqohvPz4jNq1b64QPAOP/PsUs2ZpZ7w+OLEc2WHcAEU9UxY9U/ZLSza8vHSqSNx8qEoyAeclQ8b03zL+60QNo8taauuP9CzUdN0X154LDA9XeeaqEBPRgKdGZ0sJqAvvBUasPTyFxP1LDOWi2bkXYT1YBsY1rK7SmuRErWV8CeuRaVJN07mgBhmLW0gtl2ArbIR7HoHUx9X+jPEeSy3QJyY24y02WmwutIV3ynW4RknH9xTy5a3N4l9mVfg0X0ExmC+9OfM4ZTxq7rwYyZ48ImyMVgqFV+NWD4tbbRtKtFM8UVIVvDhkIi38PgM0Thek7EdEn2G/b4RjuRiycM7pWNHUjWO7U2ERt225VoAKXo9Vn/7EQ+5Pl43/vJzpIlhEAAA=="; }
        }
    }
}
